@extends('layouts.guest')

@section('content')

<div class="container home">
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex minima adipisci ea magni expedita, modi cupiditate nihil provident illum reprehenderit reiciendis dignissimos nostrum officiis? Asperiores fugit eveniet, eos sapiente voluptates iusto porro vero, consectetur id cumque ullam illum voluptate omnis quod, alias blanditiis saepe magnam cum explicabo pariatur sint. Ullam deleniti atque doloribus tenetur possimus pariatur commodi doloremque placeat ab molestiae eius nam eligendi enim obcaecati exercitationem laborum, omnis libero quo quaerat inventore iusto facilis suscipit qui. A, velit excepturi harum provident laudantium labore suscipit necessitatibus consequatur hic, pariatur numquam, eaque minima omnis? Laudantium doloribus similique, aliquid omnis ipsum rem et, reiciendis quo vel consequatur non earum tempore ipsam consectetur sed suscipit quia fugit voluptate iste quaerat! A itaque perspiciatis iste soluta, architecto neque modi minima optio qui fugit distinctio. Quam tempora veritatis et animi amet quasi sed atque incidunt totam ducimus voluptates magni, aperiam quo minima quae eveniet nemo laudantium aut sunt? Maiores ipsum optio repellendus doloribus voluptatum enim quam expedita recusandae dicta, fugiat aperiam totam id asperiores possimus consectetur adipisci quis dignissimos iusto non commodi consequuntur! Corrupti repudiandae labore error vero nisi iusto porro omnis, possimus odio necessitatibus in accusamus incidunt deserunt eligendi modi asperiores quis! Doloribus et perspiciatis earum, velit, quod, unde rerum id quae vero animi eius deserunt quasi quam asperiores ipsa? Obcaecati temporibus ratione voluptate quisquam quidem consequuntur architecto numquam sequi enim odio magnam, vero reiciendis! Recusandae veniam ea magni sequi nihil odit fugiat sit repudiandae nemo perspiciatis vel consectetur nam iure deleniti dignissimos, sunt reiciendis suscipit repellendus consequatur? Ut accusamus rem ex asperiores fugiat facilis quam eveniet quaerat quia magni, ea expedita, veniam culpa eligendi tempore consequuntur labore, nemo quos quis. Cum ea autem iste doloremque suscipit! Dicta voluptate inventore ab qui alias deserunt provident nobis reiciendis, autem corporis vitae? Reprehenderit non adipisci nemo!</p>
</div>

@endsection
